### ISSUE TITLE
脚手架总是卡在登陆这里

### ISSUE THREAD

**Issue by DJDIDI** [serverless/serverless-tencent#120]
### BUG 描述:
脚手架总是卡在登陆这里

```
请扫码进行登陆，或通过 sls credentials 配置全局用户授权，详情请查看 sls --help
Serverless › Initializing······
```

### 复现步骤:
执行 `sls deploy` `sls info` 等命令都不会出现登陆的二维码和连接

### 预期结果:
预期出现登陆的二维码/链接

**Comment by DJDIDI** [comment]
目前复制了腾讯云的secertId 和 secertKey 到 .env文件暂时解决了

**Comment by ole3021** [comment]
@DJDIDI  

非常抱歉 给你的使用带来不便，以上代码登陆问题我们会腾讯再进行检查并提高可靠性。 

此外 也建议使用 [全局登陆 (sls credentials)](https://cn.serverless.com/framework/docs-guides-tencent-account#%E5%85%A8%E5%B1%80%E5%AF%86%E9%92%A5%E6%8E%88%E6%9D%83) 功能管理本地密钥。

**Comment by DJDIDI** [comment]
感谢官方回复
