### ISSUE TITLE
希望sls deploy能够支持http代理

### ISSUE THREAD

**Issue by lyd0** [serverless/serverless-tencent#130]
当我的shell设置了 export http_proxy=xx 代理的时候， 使用 sls deploy 命令部署 serverless 会提示 ‘ Error: an HTTP(S) proxy server `host` and `port` must be specified!  ’

![image](https://user-images.githubusercontent.com/29918052/150686989-5b9afce5-f609-4764-be86-383f779c8dbf.png)

unset 掉 http_proxy 可以正常执行，能否支持使用代理也能sls deploy？

**Comment by zongUMR** [comment]
多谢反馈，我们会对此问题进行排查

**Comment by zongUMR** [comment]
@lyd0 你好，经过排查是我们内部使用的一个工具库现在在代理情况下会有问题。 我们后面会对其进行更新修复。
当前需要您在命令行清空所有的代理配置才可以使用:
```bash
echo $HTTPS_PROXY
echo $https_proxy
echo $HTTP_PROXY
echo $http_proxy
```
---

**Comment by lyd0** [comment]
好的！谢谢你！

**Comment by ole3021** [comment]
@lyd0  非常抱歉给您的使用带来了不便，我们会尽快修复此问题，并第一时间在这里通知到您，敬请留意。
