### ISSUE TITLE
部署出现错误时 exitcode仍为0

### ISSUE THREAD

**Issue by aoyouer** [serverless/serverless-tencent#136]
### BUG 描述: 部署时出现错误但是exitcode为0

你好，我在部署的时候出现 “找不到资源”、“上传代码失败”等错误的时候，serverless deploy 这条命令的exitcode依旧为0，导致在github actions中无法判断部署是否真的成功了。
### 复现步骤:
以找不到资源的错误为例子，为了触发错误，我将配置文件中的vpc id 改为一个不存在的id，我在actions中执行了下面两条命令

```shell
serverless deploy --stage sit-beta --debug
echo "DEPLOY RESULT $?"
```
然后触发actions的部署流程。

### 预期结果:

预期结果，由于serverless deploy出错了，actions应该要显示失败，并且打印出来的 $? 应该为 1
 
### 实际结果:

![image](https://user-images.githubusercontent.com/32638818/153540260-862ec421-c933-43a0-8593-29d8ab76ebc8.png)

实际上serverless deploy 虽然出错了，但是返回值为 0.

<details>
<summary>环境版本</summary>

Environment: linux, node v14.18.3, tencent v3.20.1

Components::scf::0.9.3

</details>

**Comment by ole3021** [comment]
@aoyouer  感谢反馈该问题，我们会尽快在下个版本中修复这个问题。

**Comment by zongUMR** [comment]
@aoyouer 你好，我们已在 *serverless* 命令行工具的测试版本解决此问题。请您先安装命令行的测试版本: `npm i -g serverless@canary`. 我们会在下个正式版本中一起释出此改进。

**Comment by ole3021** [comment]
@aoyouer 你好 我们已经在最新的 Framework CLI 3.2.1 中修复了这个bug，请升级后再试试看是否还有问题。 

如果是手动升级可以使用 `npm update -g serverless` 来升级到最新的版本，如果是 CI 全新安装会自动安装最新的版本。

**Comment by aoyouer** [comment]
谢谢您的处理，问题已经解决了
