### ISSUE TITLE
网页控制台创建express示例失败

### ISSUE THREAD

**Issue by lyd0** [serverless/serverless-tencent#140]
### 在网址：  https://serverless.cloud.tencent.com/start?c=sls  中创建express示例失败

![image](https://user-images.githubusercontent.com/29918052/154520501-94bc3ee0-ac63-423a-b925-8eb7f31af54d.png)

### 失败截图：
创建的时候地区选的首尔，其他没有修改

![image](https://user-images.githubusercontent.com/29918052/154520201-2a1d16d7-7e64-4610-9281-968f56cf75e6.png)

**Comment by ole3021** [comment]
@lyd0  收到，这个问题是我们最近升级的 CLI 将运行时最低要求升级到了 node v12， 腾讯这边的系统node 版本过低导致的，我们这里会同腾讯协调一下， 尽快修复这个问题。

**Comment by lyd0** [comment]
嗯嗯 尝试了一下其他模板，也是报node版本问题

> @lyd0 收到，这个问题是我们最近升级的 CLI 将运行时最低要求升级到了 node v12， 腾讯这边的系统node 版本过低导致的，我们这里会同腾讯协调一下， 尽快修复这个问题。

**Comment by ole3021** [comment]
@lyd0  相关问题腾讯这边已经在修复，预计会在2月底发布上线。 

目前可以使用[腾讯 Serverless 控制台](https://console.cloud.tencent.com/scf/list?rid=1&ns=default&functionName=start-test-1645598804&runtime=all&keyword=all%2Call)进行部署

或者通过 Serverless CLI 在[本地初始化并部署](https://cn.serverless.com/framework/docs-components-website)。
