### ISSUE TITLE
github workflows执行sls deploy没有成功

### ISSUE THREAD

**Issue by lyd0** [serverless/serverless-tencent#143]
和这个issues类似 github workflows执行sls deploy也没有成功 https://github.com/serverless/serverless-tencent/issues/142#issue-1142586504
.env文件配置了账号信息，请问是还需要一些什么配置吗？
结果截图：
![image](https://user-images.githubusercontent.com/29918052/154645926-adcd41fd-d3fa-4d10-ae0d-4cf1ec0395ff.png)

**Comment by zongUMR** [comment]
Related to https://github.com/serverless/serverless-tencent/issues/142, close this one.
