### ISSUE TITLE
flask模板问题

### ISSUE THREAD

**Issue by lyd0** [serverless/serverless-tencent#151]
按照  [官方flask模板](https://cloud.tencent.com/document/product/583/58367) 跑代码，本地和腾讯云serverless都报以下错误

```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from flask import Flask, jsonify
  File "/var/user/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/var/user/flask/app.py", line 25, in <module>
    from . import cli, json
  File "/var/user/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json'
```
可能是官方推荐的flask版本太低导致的：
![image](https://user-images.githubusercontent.com/29918052/156739717-d4cbb30e-a985-4d77-a06a-159172041f5f.png)

升级flask和werkzeug的版本，在本地可以运行，但是腾讯云serverless又没办法运行werkzeug，请问需要如何配置？

**Comment by ole3021** [comment]
@lyd0  你好， 我在 werkzeug 2.x 的网站上看到 官方说明的运行时要求是 Python 3.6 之上 `Requires: Python >=3.6 `。 应该是可以运行。 麻烦确认一下是否是运行时导致的问题， 如果需要使用更高级的运行时，可以在 `serverless.yml`中修改运行时信息，目前支持的运行时有：

      - Python2.7
      - Python3.6
      - Python3.7
      - Nodejs6.10
      - Nodejs8.9
      - Nodejs10.15
      - Nodejs12.16
      - Nodejs14.18
      - Nodejs16.13
      - Php5
      - Php7
      - Php7.4
      - Php8.0
      - Go1
      - Java8
      - Java11
      - CustomRuntime

![图片](https://user-images.githubusercontent.com/2676686/156750732-e7757952-0740-4b09-ab55-eb0dcb87db10.png)

**Comment by lyd0** [comment]
> @lyd0 你好， 我在 werkzeug 2.x 的网站上看到 官方说明的运行时要求是 Python 3.6 之上 `Requires: Python >=3.6 `。 应该是可以运行。 麻烦确认一下是否是运行时导致的问题， 如果需要使用更高级的运行时，可以在 `serverless.yml`中修改运行时信息，目前支持的运行时有：
> 
> ```
>   - Python2.7
>   - Python3.6
>   - Python3.7
>   - Nodejs6.10
>   - Nodejs8.9
>   - Nodejs10.15
>   - Nodejs12.16
>   - Nodejs14.18
>   - Nodejs16.13
>   - Php5
>   - Php7
>   - Php7.4
>   - Php8.0
>   - Go1
>   - Java8
>   - Java11
>   - CustomRuntime
> ```
> 
> ![图片](https://user-images.githubusercontent.com/2676686/156750732-e7757952-0740-4b09-ab55-eb0dcb87db10.png)

您好 我试了一下换python3.7没有解决，我使用3.6或者3.7将Flask和werkzeug升级最新，然后安装dataclasses解决了问题，但是现在体验还是不太好，在本地需要每次删除dataclasses的py文件才能跑，部署到云服务器需要下载dataclasses的python 文件才能跑

**Comment by lyd0** [comment]
@ole3021 [ole3021](https://github.com/ole3021)您好 我试了一下换python3.7没有解决，我使用3.6或者3.7将Flask和werkzeug升级最新，然后安装dataclasses解决了问题，但是现在体验还是不太好，在本地需要每次删除dataclasses的py文件才能跑，部署到云服务器需要下载dataclasses的python 文件才能跑

**Comment by ole3021** [comment]
@lyd0 好的，这个问题我会记录并反馈到腾讯的SCF相关同事，后面会优化一下，优化结果也会在这里更新。 感谢您的反馈。

**Comment by lyd0** [comment]
好的 谢谢
