### ISSUE TITLE
sls deploy 支持region

### ISSUE THREAD

**Issue by hellojuly** [serverless/serverless-tencent#164]
目前serveless.yml文件内region字段只能硬编码，希望sls deploy 支持一下--region参数。

`sls deploy --region ap-shanghai`

**Comment by timqian** [comment]
@hellojuly 可以通过 --inputs 命令 serverless.yml 中的配置
例如：
```
sls deploy --inputs region=ap-shanghai
```

文档：https://cn.serverless.com/framework/docs-commands-deploy

**Comment by hellojuly** [comment]
感谢@timqian， `--inputs`参数覆盖region能够生效。

但似乎`--inputs`不能和`--target`共用，如果一起使用将导致.env内配置被忽略。

例如：
`sls deploy --target=.serverless --inputs region=ap-shanghai`
将提示进行临时扫码授权

如果替换为
```
cd .serverless
sls deploy --inputs region=ap-shanghai
```
则能够正常读取.env。

**Comment by timqian** [comment]
@hellojuly 我尝试了一下，你遇到的这个问题应该与 `--inputs` 参数无关

`--target` 主要是用于多组件应用的部署。所以不会影响读取 `.env` 环境的逻辑。
当执行这个命令时
`sls deploy --target=.serverless`
sls 会从当前目录下或者当前目录的父级目录寻找 `.env` 文件，所以没有找到。

你可以把 `.env` 放在当前目录试试，或者使用 [`sls credentials`](https://cn.serverless.com/framework/docs-commands-credentials) 命令定义全局 secrets 方便使用

**Comment by ole3021** [comment]
@hellojuly  相关内容已经发布，现在 target 可以正确读取到指定目录的 .env 配置

**Comment by hellojuly** [comment]
收到，大佬辛苦了☕️  @ole3021
