### ISSUE TITLE
部署时， --config 选项不管用

### ISSUE THREAD

**Issue by waymao** [serverless/serverless-tencent#21]
### BUG 描述:

https://www.serverless.com/framework/docs/providers/tencent/cli-reference/deploy/ 
文档中说明 `--config` 选项可以自行指定一个配置文件。

然而实际操作中发现，此选项似乎没有用。

### 复现步骤:

0. 一切操作前运行`sls deploy`，应用可以成功部署。
1. 重命名 `serverless.yml` 为 `serverless2.yml`
2. 执行 `sls deploy --config serverless2.yml`

### 预期结果:

使用`serverless2.yml`中的参数并成功部署

### 实际结果:

报错，没有找到serverless配置文件

### 调试信息:

<details>
<summary>环境版本</summary>

```yaml
- requestId: 无
- traceId: 无
- 操作系统(OS): CentOS 7
- Node 版本:  14.17.1
- Framework Core: 2.48.1
- Plugin: 5.4.2
- SDK: 4.2.3
- Components: 3.12.0
```

</details>

---

<details>
<summary>serverless.yml 配置</summary>

```yaml
# 在这里填写完整的serverless.yml配置信息
```

</details>

---

<details>
<summary>DEBUG 输出</summary>

```
正在初始化...

 Error: 没有找到serverless配置文件，请检查。
    at Object.checkBasicConfigValidation (/usr/local/share/.config/yarn/global/node_modules/@serverless/components/src/cli/commands-cn/utils.js:54:11)
    at Object.module.exports [as run] (/usr/local/share/.config/yarn/global/node_modules/@serverless/components/src/cli/commands-cn/run.js:53:15)
    at async Object.module.exports (/usr/local/share/.config/yarn/global/node_modules/@serverless/components/src/cli/index.js:197:7)

Serverless › 没有找到serverless配置文件，请检查。

  帮助文档: https://www.serverless.com/cn/framework/docs/
  BUG提交: https://github.com/serverless/serverless-tencent/issues
  问答社区: https://github.com/serverless/serverless-tencent/discussions
```

</details>

### 额外信息

我们之所以要使用多个serverless文件是因为我们把我们django服务分拆成三个小部件部署。而目前如果--config无效的话，我们只能通过脚本临时移动重命名文件来实现，存在一定的麻烦。

**Comment by ole3021** [comment]
@waymao  你好， 目前中国的Serverless 都是基于组件（components）构建的，与AWS的传统Serverless上存在的一些不同， --config目前并没有再组件模式中提供支持。 

对于组件的使用，我们是支持多组件管理模式的，也就是在一个应用中可以包含多个组件，每个组件相当于一个单独的服务。 可以查看 [项目结构](https://www.serverless.com/cn/framework/docs/basic/project-structure/) 获得更多说明。 同时也可以参考 [fullstack应用开发案例](https://github.com/serverless-components/tencent-examples/tree/master/fullstack) 如果可以进行函数开发，也可以参考我们最近刚刚发布的[多函数组件示例](https://github.com/serverless-components/tencent-examples/tree/master/multi-scf-nodejs)。

如果以上没有解决你的问题，也可以加我微信 `b2xlMzAyMQ==` (base64) 进一步沟通你的使用中的问题。
