### ISSUE TITLE
无法访问正常的serverless网站看文档，直接跳转cn.serverless.com

### ISSUE THREAD

**Issue by nervending** [serverless/serverless-tencent#70]
### BUG 描述:
无法访问正常的serverless网站看文档，直接跳转cn.serverless.com

### 复现步骤:
浏览器访问 https://serverless.com/framework/docs/ 直接自动跳转，且无法自己选择访问的是哪个站点，看到的都是关于腾讯部分的文档，能不能干点人事

### 预期结果:
正常访问serverless 文档

### 实际结果:
什么鬼，你自己说说 干的是啥事，让用其他平台的人怎么用

### 调试信息:
what the fuck!!!!!

**Comment by nervending** [comment]
真的过粪了，贴片、弹窗，宣传腾讯云对serverless支持做的好，都可以，哪有走别人的路让别人无路可走的。

**Comment by ole3021** [comment]
@nervending  Serverless的全球英文官网主要是针对AWS的海外用户提供的 Serverless 开发解决访问。默认是IP为非中国地区的用户可以访问，对于IP来自中国的用户回默认显示中文网站，并且中国的 Serverless 开发解决方案是以腾讯云为基础的解决方案。 

目前 Serverless 网站刚刚升级，相关的地区和语言切换功能还没有完成导致使用不便尽请见谅。

如果需要访问全球官方可以使用海外IP访问，或使用地址 https://wb.serverless.com 进行访问（不限制用户ip地址）

**Comment by nervending** [comment]
呵呵，呵呵哒，你真棒！
