### ISSUE TITLE
新建Wordpress框架应用失败

### ISSUE THREAD

**Issue by sfc9982** [serverless/serverless-tencent#95]
### BUG 描述:

新建Wordpress框架应用失败

### 复现步骤:

MySQL配置北京五区的云服务器上，已开放公网访问权限
新建Serverless应用时选择了同一区（北京五区）。

部署时报错：

```
 Error: [INIT ERROR]: [Serverless DB Error]: Intialize failed.
     at ServerlessComponent.deploy (/var/user/serverless.js:259:13)
     at process._tickCallback (internal/process/next_tick.js:68:7)

 42s › wordpress-8c687z0Dc › [INIT ERROR]: [Serverless DB Error]: Intialize failed. 
```

内网模式-填写服务器内网IP
公网模式-填写服务器公网IP
均尝试

谢谢帮助

### 预期结果:

创建成果

### 实际结果:

失败，信息见报错

### 调试信息:

```
构建ID：14164429

[2021-12-17 17:49:18] CI_BUILD_ID=14164429
[2021-12-17 17:49:18] JOB_ID=965455
```

日志节选：https://pastebin.com/hxu9dDts
（上传时未脱敏，密码已改）

### 额外信息

使用腾讯云Serverless面板创建

**Comment by Jominja** [comment]
请检查‘wp’用户的**_密码_**是否正确以及是否包含**_建库和建表_**权限

**Comment by ole3021** [comment]
@sfc9982  麻烦检查一下相关账号的密码和访问权限信息，如果后续还有任何问题也欢迎继续反馈到我们。多谢。
